# Generated by Django 4.0.4 on 2022-05-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0004_todos_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('mail', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
