# Generated by Django 4.0.4 on 2022-05-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0005_sign_up'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_up',
        ),
    ]
